main:
	@gcc -Wstack-protector $(CPPFLAGS) $(CFLAGS) $(LDFLAGS) -DPT_METAPHONE_MAIN -o metaphone_ptbr metaphone_ptbr.c
# gcc -DPT_METAPHONE_MAIN -o metaphone_ptbr metaphone_ptbr.c

clean:
	@rm -f metaphone_ptbr *.o
